### ISSUE TITLE
Problem to access to data in __getitem__ UBFC dataset

### ISSUE THREAD

**Issue by italosalgado14** [Dylan-H-Wang/SLF-RPM#2]
Hi! Thanks for the code. I try to train your model, but i dont understand  how you charge the videos/txt to train.
In "dataset.py" line 169: 
```
    def __getitem__(self, idx: int):
        with np.load(self.files[idx], allow_pickle=True) as f:
            data = f["frames"][:self.vid_frame:self.vid_frame_stride]
            label = f["hr"].astype(np.float32)
```
There you try to open a list of archives: 
```
files = ['ubfc-rppg/DATASET_2/subject1/vid.avi', 'ubfc-rppg/DATASET_2/subject1/ground_truth.txt', etc...]
```
But numpy complains of the following:

```
OSError: Failed to interpret file 'ubfc-rppg/DATASET_2/subject25/ground_truth.txt' as a pickle  (pickle.UnpicklingError: invalid load key, ' ')
```
or

```
OSError: Failed to interpret file 'ubfc-rppg/DATASET_2/subject11/vid.avi' as a pickle (pickle.UnpicklingError: unpickling stack underflow)
```
is an error of my version of numpy or some other problem?
Thanks in advance.

**Comment by Dylan-H-Wang** [comment]
Hi,

Please check the `utils/utils.py` file [here](https://github.com/Dylan-H-Wang/SLF-RPM/blob/03afe0fdd139566e4436ce6026aec5fe7f44adaa/utils/utils.py#L311)  which process the videos and ground truth and convert them into pickle files.

Cheers

**Comment by italosalgado14** [comment]
Thanks for the reply. Indeed the *utils.py* file contains the function *extract_ubfc_dataset()* to transform the dataset. Closed
